module myModule {
    const string TOPIC_MYMESSAGE = "MyMessageTopicName";
    const long FIVEENUMS_LENGTH = 5;

    enum MyEnum {
        MyEnum_One,
        MyEnum_Two
    };

    struct myError {
        long Id;
        string Description;
        boolean TheBool;
        sequence<boolean, 10> TenBools;
    };

    union myUnion switch (MyEnum) {
    case MyEnum_One:
        boolean theBool;
    case MyEnum_Two:
        myError theError;
    };

    struct myMessage {
        short theShort;
        unsigned short theUnsignedShort;

        long theLong;
        unsigned long theUnsignedLong;

        float theFloat;
        double theDouble;

        boolean theBool;

        string Text;

        myError Error;

        MyEnum theEnum;

        sequence<MyEnum, FIVEENUMS_LENGTH> FiveEnums;

        myUnion theUnion;
    };
};
